# ── JPA / Hibernate ───────────────────────────────────
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── Thymeleaf ─────────────────────────────────────────
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# ── アプリ設定 ────────────────────────────────────────
server.port=8080
spring.application.name=sudoku-app

# SQLite──────────────────────────────────
spring.sql.init.mode=always
spring.datasource.url=jdbc:sqlite::resource:sudoku.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect